### ISSUE TITLE
Responsive videos

### ISSUE THREAD

**Issue by bmeurer** [v8/v8.dev#104]
Our (youtube) video embeds don't preserve aspect ratio properly. This could be fixed with `markdown-it-video` and proper CSS (<https://github.com/bmeurer/benediktmeurer.de/commit/f6054bd6d88d4ec4ae728a41d6605abfaebb4078> gives an idea). The difference can be seen between <https://v8.dev/blog/fast-async> and <https://benediktmeurer.de/2018/11/12/faster-async-functions-and-promises/> on a phone or in DevTools using the *Toggle device toolbar* feature.

**Comment by mathiasbynens** [comment]
I just went through all YouTube embeds on v8.dev and confirmed they're all 16:9 (or at least, the YouTube Embed snippet for each of them outputs a 16:9-ratio'd `iframe`).

Note that making the videos responsive is trickier than just the examples you've highlighted, since some of our videos have `<figcaption>`s. Example: https://v8.dev/blog/tracing-js-dom#devtools-heap-snapshot 

```html
<figure>
  <iframe></iframe>
  <figcaption></figcaption>
</figure>
```

If we position the `iframe` absolutely within the `figure`, how do we position the `figcaption` correctly without knowing how many lines of text it fills up?

**Comment by mathiasbynens** [comment]
I caved and added a `<div>` around the `<iframe>` in https://github.com/v8/v8.dev/pull/112. PTAL :)
